// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nzgfiuoegvksmbvvlglj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im56Z2ZpdW9lZ3Zrc21idnZsZ2xqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ5MjY1MTgsImV4cCI6MjA3MDUwMjUxOH0.N402jIAGSyrgWg8NjRHlnE9yvbmuA26QxSctyHjfNpQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});